#############################################################################
#
# Non-leaf subdirectiory Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# settings common to this part of the subdirectory tree
TARGET         ?= arduino-due

# set RELATIVE to the next higher directory and defer to the Makefile.link
RELATIVE := ..
include $(RELATIVE)/Makefile.link

